#!/bin/env bash

function info()    { ${INFO-true} && echo $* || true; }
function verbose() { ${VERBOSE-false} && echo $* || true; }
function debug()   { ${DEBUG-false} && echo $* || true; }
function error() { echo ERROR 1>&2 $*; exit 1; }

encrypt_str() {
    echo $( echo $1 | openssl aes-256-cbc -a -A -salt -pbkdf2 -pass pass:$SAVV_PASSWORD )
}

decrypt_str() {
    echo $( echo $1 | openssl aes-256-cbc -d -a -A -pbkdf2 -pass pass:$SAVV_PASSWORD )
}

generate_password() {
    if [[ -z $1 ]]; then
        length=32
    elif [[ $1 == g* ]]; then
        length=32
    else
        length=${1#@generate:}
    fi
    secret=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $length | head -n 1)
}

view_file() {
    cat $1 | while read -r line; do
        if [[ ${line/decrypt_str} == $line ]]; then
            printf "%s\n" "$line"
        else
            varname=${line%=\$(decrypt_str*}
            secured=${line#*\$(decrypt_str }
            secured=${secured%)}
            value=$(decrypt_str $secured)
            printf "%s\n" "$line" | sed  -e "s|\$(decrypt_str $secured)|@savv($value)|"
        fi
    done
}

parse_savv_command() {
    local savv_line=$1
    local cmd=${savv_line%:*}
    local remainder=${savv_line##*:}
    case $cmd in
        e|enc|encrypt)
            secret=$remainder
            ;;
        m|mod|modify)
            modify $remainder
            ;;
        g|gen|generate)
            generate_password $remainder
            ;;
        r|read)
            echo Provide secret for $line
            read -u 0 -s secret
            ;;
        *)  # Default case nothing to do, signalled by empty secret
            unset secret
    esac
}

secure_file() {
    FILE=$1
    info securing $FILE
    cat $FILE | while read line; do
        #printf "%s" $line
        savv_cmd=${line#*@savv:}
        parse_savv_command $savv_cmd
        if [[ -z $secret ]]; then
            new_line=$line
        else
            secured=$(encrypt_str $secret)
            if ${DRY_RUN:-false}; then
                echo $line | sed -e "s|@savv($value)|\$(decrypt_str $secured)|"
            elif ${INLINE:-true}; then
                echo securing ${line/@savv:*/@savv:$savv_cmd:...}
                # replace / in line with \/ for sed search
                line=${line//\//\\\/}
                sed -i -e "/$line/s|@savv:.*|\$(decrypt_str $secured)|" $FILE
            fi
        fi
    done
}

show_help() {
cat <<EOF
Usage: ${0##*/} [options] <file>...

The purpose of savv is working with encrypted (shell) variables
Options can be:
    -h|--help               display this help and exit
    -p|--password           provide a password for encryption/decryption
    -g|-generate[:<len>]    generate a random string of provided length (default 32) and exit
    -r|--reverse            reverse the encyption to view in a format to easily edit
    -v|--view               view the decrypted values in a format that can be used in scripts
    -n|--no-change          don't change the file, output changes (dry-run)

If none of the --generate, --reverse or --export options are given, the default mode is to encrypt.
In this mode single variables that are prefixed with @savv are encrypted. Examples are
    export VAR1=@savv:encrypt:secret1
    export VAR2=@savv:read
    export VAR3=@savv:generate
    export VAR4=@savv:generate:64
A label of @savv:read will ask the user for a password.
A label of @savv:generate will generate a password of length 32
The lines will be replaced with something like:
    VAR1=\$(decrypt_str ...)

When using the --export option the vars are output in decrypted format. This output can be used in a script, e.g.
    eval \$(savv -e -p \$SAVV_MASTER_PASSWORD  ~/savv-passwords)

The decrypt_str is a function with the following defintion
    decrypt_str() {
        echo \$( echo $1 | openssl aes-256-cbc -d -a -A -pbkdf2 -pass pass:\$SAVV_PASSWORD )
    }
EOF
}
command=secure_file
while [ ! $# -eq 0 ]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -p|--password)
            if [[ -z ${2-} ]] ; then
                echo options --password and -p need an password as argument
                exit 1
            fi
            SAVV_PASSWORD=$2
            shift
            ;;
        -g*|--generate*)
            echo $(generate_password ${1/*:/@generate:})
            exit 0
            ;;
        -r|--reverse)
            command=reverse_vars
            ;;
        -v|--view)
            command=view_file
            ;;
        -n|--no-change)
            DRY_RUN=true
            ;;
        *)  # Default case: No more options, so break out of the loop.
            break
    esac
    shift
done

if [[ -z $SAVV_PASSWORD ]]; then
    echo SAVV_PASSWORD is not defined, use the following statements
    printf "  export SAVV_PASSWORD"
    printf "  read -s SAVV_PASSWORD"
        exit 1
elif [[ $SAVV_PASSWORD == @read ]]; then
    echo enter the password
    read -s SAVV_PASSWORD
elif [[ $SAVV_PASSWORD == @generate ]]; then
    SAVV_PASSWORD=$(generate_password)
    echo enncrypting variables with generated key $SAVV_PASSWORD
fi


for file in $@; do
    $command $file
done
